name: Build APK

on:
  push:
    branches: [ feature/auto-blacklist-updates ]
    paths-ignore:
      - '**.md'
      - '**.txt'
      - 'docs/**'
      - '.gitignore'
      - 'LICENSE'
  pull_request:
    branches: [ feature/auto-blacklist-updates ]
    paths-ignore:
      - '**.md'
      - '**.txt'
      - 'docs/**'
      - '.gitignore'
      - 'LICENSE'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Cache Gradle dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Debug APK
      run: ./gradlew assembleVanillaDebug --no-daemon --stacktrace
      
    - name: Build Release APK
      run: ./gradlew assembleVanillaRelease --no-daemon --stacktrace

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: aurora-updater-debug-${{ github.sha }}
        path: app/build/outputs/apk/vanilla/debug/*.apk
        retention-days: 30
        
    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: aurora-updater-release-${{ github.sha }}
        path: app/build/outputs/apk/vanilla/release/*.apk
        retention-days: 30

    - name: Get commit SHA
      id: vars
      run: echo "sha_short=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_OUTPUT

    - name: Add build summary
      run: |
        echo "📱 **APK Build Complete!**" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Debug APK:**" >> $GITHUB_STEP_SUMMARY
        ls -la app/build/outputs/apk/vanilla/debug/*.apk >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Release APK:**" >> $GITHUB_STEP_SUMMARY
        ls -la app/build/outputs/apk/vanilla/release/*.apk >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "✨ **Features in this build:**" >> $GITHUB_STEP_SUMMARY
        echo "- 🔄 Auto-blacklist updates every 15 seconds" >> $GITHUB_STEP_SUMMARY
        echo "- 🚀 Automatic UI refresh when blacklist changes" >> $GITHUB_STEP_SUMMARY
        echo "- 🎯 Smart change detection (only updates when needed)" >> $GITHUB_STEP_SUMMARY
        echo "- 🔧 Removed blacklist password protection" >> $GITHUB_STEP_SUMMARY
        echo "- 📡 Fixed GitHub API integration with proper URL" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "📦 Download the artifacts from the Actions tab above!" >> $GITHUB_STEP_SUMMARY